name: the less i know the better...

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: yess
      uses: actions/checkout@v3

    - name: cranky
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: the less i know the better
      run: |
        rustc index.rs
        ./index

    - name: another annoying ass reminder that everything is not eternal
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "update year progress" || echo "no need writing then"
        git push