name: the less i know the better...

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: nyessss.....
      uses: actions/checkout@v3

    - name: compile the script
      run: |
        gcc main.c -o main
        ./main

    - name: the end...
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "another reminder that nothing is eternal" || echo "new person, same old mistakes"
        git push